-- MySQL Script generated by MySQL Workbench
-- qua 30 ago 2023 20:04:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MED-FACIL
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MED-FACIL` ;

-- -----------------------------------------------------
-- Schema MED-FACIL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MED-FACIL` ;
USE `MED-FACIL` ;

-- -----------------------------------------------------
-- Table `MED-FACIL`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`usuario` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`admin` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admin_usuario_idx` (`usuario_id` ASC) ,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) ,
  CONSTRAINT `fk_admin_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `MED-FACIL`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`cidadao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`cidadao` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`cidadao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paciente_usuario1_idx` (`usuario_id` ASC) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) ,
  CONSTRAINT `fk_paciente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `MED-FACIL`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`pedido` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_remedio` VARCHAR(100) NOT NULL,
  `uso` ENUM('continuo', 'pre-datado') NOT NULL,
  `quantidade` FLOAT NOT NULL,
  `receita` VARCHAR(45) NOT NULL,
  `cidadão_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_cidadão1_idx` (`cidadão_id` ASC) ,
  CONSTRAINT `fk_pedido_cidadão1`
    FOREIGN KEY (`cidadão_id`)
    REFERENCES `MED-FACIL`.`cidadao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`remedio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`remedio` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`remedio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `denominacao` VARCHAR(500) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`remedio_has_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`remedio_has_pedido` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`remedio_has_pedido` (
  `remedio_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`remedio_id`, `pedido_id`),
  INDEX `fk_remedio_has_pedido_pedido1_idx` (`pedido_id` ASC) ,
  INDEX `fk_remedio_has_pedido_remedio1_idx` (`remedio_id` ASC) ,
  CONSTRAINT `fk_remedio_has_pedido_remedio1`
    FOREIGN KEY (`remedio_id`)
    REFERENCES `MED-FACIL`.`remedio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_remedio_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `MED-FACIL`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`estado` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`estado` (
  `id` INT NOT NULL,
  `nome_estado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`cidade` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cidade` VARCHAR(100) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC) ,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `MED-FACIL`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`ubs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`ubs` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`ubs` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '\n',
  `nome_ubs` VARCHAR(100) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ubs_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_ubs_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `MED-FACIL`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`endereco` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  `ubs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enderco_usuario1_idx` (`usuario_id` ASC) ,
  INDEX `fk_endereco_ubs1_idx` (`ubs_id` ASC) ,
  CONSTRAINT `fk_enderco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `MED-FACIL`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_ubs1`
    FOREIGN KEY (`ubs_id`)
    REFERENCES `MED-FACIL`.`ubs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`pedido_has_remedio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`pedido_has_remedio` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`pedido_has_remedio` (
  `pedido_id` INT NOT NULL,
  `remedio_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`, `remedio_id`),
  INDEX `fk_pedido_has_remedio_remedio1_idx` (`remedio_id` ASC) ,
  INDEX `fk_pedido_has_remedio_pedido1_idx` (`pedido_id` ASC) ,
  CONSTRAINT `fk_pedido_has_remedio_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `MED-FACIL`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_remedio_remedio1`
    FOREIGN KEY (`remedio_id`)
    REFERENCES `MED-FACIL`.`remedio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MED-FACIL`.`pedido_has_remedio1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MED-FACIL`.`pedido_has_remedio1` ;

CREATE TABLE IF NOT EXISTS `MED-FACIL`.`pedido_has_remedio1` (
  `pedido_id` INT NOT NULL,
  `remedio_id` INT NOT NULL,
  PRIMARY KEY (`pedido_id`, `remedio_id`),
  INDEX `fk_pedido_has_remedio1_remedio1_idx` (`remedio_id` ASC) ,
  INDEX `fk_pedido_has_remedio1_pedido1_idx` (`pedido_id` ASC) ,
  CONSTRAINT `fk_pedido_has_remedio1_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `MED-FACIL`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_remedio1_remedio1`
    FOREIGN KEY (`remedio_id`)
    REFERENCES `MED-FACIL`.`remedio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO remedio VALUES 
(1,'abacavir (sulfato de abacavir)','solução oral, 20 mg/mL frasco'),
(2,'abatacepte','injetável, 125 mg seringa preenchida'),
(3,'abatacepte','injetável, 250 mg frasco- ampola'),
(4,'abciximabe','injetável, 2 mg/mL frasco ampola'),
(5,'acetato de sódio','injetável, 2 mEq/mL ampola'),
(6,'acetazolamida','comprimido 250mg'),
(7,'acetazolamida','comprimido 250mg'),
(8,'aciclovir','comprimido 200 mg'),
(9,'aciclovir','creme 50 mg/g (5%)'),
(10,'aciclovir','injetável, 250 mg frasco- ampola'),
(11,'aciclovir','comprimido 200 mg'),
(12,'aciclovir','comprimido 200 mg'),
(13,'ácido acetilsalicílico','comprimido 100 mg'),
(14,'ácido acetilsalicílico','comprimido 500 mg'),
(15,'ácido ascórbico','solução oral, 200 mg/mL frasco'),
(16,'ácido fólico','comprimido 5 mg'),
(17,'ácido fólico','comprimido 5 mg'),
(18,'ácido fólico','solução oral 0,2 mg/mL frasco'),
(19,'ácido folínico (folinato de cálcio)','comprimido 15 mg'),
(20,'ácido folínico (folinato de cálcio)','comprimido 15 mg'),
(21,'ácido nicotínico','comprimido de liberação prolongada 500 mg'),
(22,'ácido paraminossalicílico','granulado oral, 4 g envelope'),
(23,'ácido salicílico','pomada 50 mg/g (5%)'),
(24,'ácido tranexâmico','comprimido 250 mg'),
(25,'ácido tricloacético','solução tópica, frasco'),
(26,'ácido ursodesoxicólico','comprimido 50 mg'),
(27,'ácido ursodesoxicólico','comprimido 150 mg'),
(28,'ácido ursodesoxicólico','comprimido 300 mg'),
(29,'ácido valpróico (valproato de sódio)','comprimido ou cápsula 250 mg'),
(30,'ácido valpróico (valproato de sódio)','cápsula 250 mg'),
(31,'ácido valpróico (valproato de sódio)','comprimido 500 mg'),
(32,'ácido valpróico (valproato de sódio)','solução oral, 50 mg/mL frasco'),
(33,'ácido valpróico (valproato de sódio)','xarope, 50 mg/mL frasco'),
(34,'ácido zoledrônico','injetável, 5 mg/100mL frasco'),
(35,'acitretina','cápsula 10 mg'),
(36,'acitretina','cápsula 25 mg'),
(37,'adalimumabe','injetável, 40mg frasco ampola (uso pediátrico)'),
(38,'adalimumabe','injetável, 40 mg seringa preenchida'),
(39,'água para injetáveis','injetável, ampola de 5 mL'),
(40,'água para injetáveis','injetável, ampola  de 10 mL'),
(41,'água para injetáveis','injetável, frasco de 100 mL'),
(42,'água para injetáveis','injetável, frasco de 500 mL'),
(43,'agulha para caneta aplicadora de insulina','unidade'),
(44,'albendazol','comprimido mastigável 400 mg'),
(45,'albendazol','suspensão oral, 40 mg/mL frasco'),
(46,'albumina humana','injetável, 0,2 g/mL
(20%) frasco'),
(47,'alcachofra (Cynara scolymus L.)','cápsula, comprimido,
drágea, solução oral e tintura (24 a 48mg de derivados de ácido cafeoilquínico expressos em ácido clorogênico - dose diária)'),
(48,'alcatrão mineral','pomada 10 mg/g (1%)'),
(49,'álcool etílico','gel 70%'),
(50,'álcool etílico','solução 70%'),
(51,'alendronato de sódio','comprimido 10 mg'),
(52,'alendronato de sódio','comprimido 70 mg'),
(53,'alendronato de sódio','comprimido 70 mg'),
(54,'alfa-alglicosidase','injetável, frasco-ampola com 50 mg de pó liofilizado'),
(55,'alfacalcidol','cápsula 0,25 mcg *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(56,'alfacalcidol','cápsula 1,0 mcg *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(57,'alfadornase','solução para inalação, 1mg/mL ampola'),
(58,'alfaelosulfase','injetável, 1mg/mL frasco de 5mL'),
(59,'alfaepoetina','injetável, 1.000 UI
frasco ampola *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar finalização de processo
licitatório.'),
(60,'alfaepoetina','injetável, 2.000 UI frasco ampola'),
(61,'alfaepoetina','injetável, 3.000 UI
frasco ampola *item atualmente sem demanda. Após abertura (fluxo NP)e deferimento do processo, seu fornecimento deverá aguardar finalização de processo
licitatório.'),
(62,'alfaepoetina','injetável, 4.000 UI frasco ampola'),
(63,'alfaepoetina','injetável, 10.000 UI frasco ampola'),
(64,'alfainterferona 2b','injetável, 3.000.000 UI frasco ampola'),
(65,'alfainterferona 2b','injetável, 5.000.000 UI
frasco ampola  *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(66,'alfainterferona 2b','injetável, 10.000.000 UI
frasco ampola  *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(67,'alfapeginterferona 2a','injetável, 180 mcg seringa preenchida'),
(68,'alfapeginterferona 2b','injetável, 80 mcg frasco ampola'),
(69,'alfapeginterferona 2b','injetável, 100 mcg frasco ampola'),
(70,'alfapeginterferona 2b','injetável, 120 mcg frasco-ampola'),
(71,'alfataliglicerase','injetável, 200 UI frasco- ampola'),
(72,'alfaporactanto (surfactante pulmonar)','suspensão injetável
intratecal ou intrabrônquica, 80 mg/mL frasco ampola'),
(73,'alfavelaglicerase','injetável, 400 UI frasco ampola'),
(74,'alopurinol','comprimido 100 mg'),
(75,'alopurinol','comprimido 300 mg'),
(76,'alteplase','injetável, 10 mg frasco ampola'),
(77,'alteplase','injetável, 20 mg frasco ampola'),
(78,'alteplase','injetável, 50 mg frasco ampola'),
(79,'amantadina','comprimido 100 mg'),
(80,'ambrisentana','comprimido 5 mg'),
(81,'ambrisentana','comprimido 10mg'),
(82,'amicacina (sulfato de amicacina)','injetável, 250 mg/ml ampola'),
(83,'amiodarona (cloridrato de amiodarona)','comprimido 200 mg'),
(84,'amiodarona (cloridrato de amiodarona)','injetável, 50 mg/mL ampola'),
(85,'amitriptilina (cloridrato de amitriptilina)','comprimido 25 mg'),
(86,'amitriptilina (cloridrato de amitriptilina)','comprimido 25 mg'),
(87,'amitriptilina (cloridrato de amitriptilina)','comprimido 75 mg'),
(88,'amoxicilina','cápsula 500 mg'),
(89,'amoxicilina','suspensão oral, 50 mg/mL frasco'),
(90,'amoxicilina + clavulanato de potássio','comprimido 500 mg + 125 mg'),
(91,'amoxicilina + clavulanato de potássio','suspensão oral, (50 mg
+ 12,5 mg)/mL frasco'),
(92,'anfotericina B (complexo lipídico)','injetável, 5 mg/mL frasco ampola'),
(93,'anfotericina B (lipossomal)','injetável, 50 mg frasco ampola'),
(94,'anlodipino','comprimido 5 mg'),
(95,'anlodipino','comprimido 10 mg'),
(96,'antimoniato de meglumina','injetável, 300 mg/mL ampola'),
(97,'aroeira (Schinus terebenthifolius Raddi)','gel e óvulo vaginal (1,932 mg de ácido gálico - dose diária)'),
(98,'artemeter+ lumefantrina','comprimido 20 mg + 120 mg'),
(99,'artesunato','injetável, 60 mg/mL frasco-ampola'),
(100,'artesunato + cloridrato mefloquina','comprimido (25 + 55)mg'),
(101,'artesunato + cloridrato mefloquina','comprimido (100 + 220)mg'),
(102,'atazanavir (sulfato de atazanavir)','cápsula  300 mg'),
(103,'atenolol','comprimido 50 mg'),
(104,'atenolol','comprimido 100 mg'),
(105,'atorvastatina','comprimido 10mg'),
(106,'atorvastatina','comprimido 20mg'),
(107,'atorvastatina','comprimido 40 mg'),
(108,'atorvastatina','comprimido 80 mg *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(109,'atropina (sulfato de atropina)','injetável, 0,25 mg/mL ampola'),
(110,'azatioprina','comprimido 50 mg'),
(111,'azitromicina','comprimido 250 mg'),
(112,'azitromicina','comprimido 500 mg'),
(113,'azitromicina','suspensão oral, 40 mg/mL frasco'),
(114,'aztreonam lysine','solução inalatória, 75 mg'),
(115,'babosa [Aloe vera (L.) Burm. f. ]','creme e gel (10-70% gel fresco)'),
(116,'baricitinibe','comprimido 2 mg'),
(117,'baricitinibe','comprimido 4 mg'),
(118,'basiliximabe','injetável, 20 mg frasco ampola'),
(119,'beclometasona (dipropionato de beclometasona)','solução para inalação oral 50 mcg/dose'),
(120,'beclometasona (dipropionato de beclometasona)','suspensão para inalação nasal 50 mcg/dose'),
(121,'beclometasona (dipropionato de beclometasona)','pó para inalação oral 200 mcg/dose'),
(122,'beclometasona (dipropionato de beclometasona)','solução para inalação oral 200 mcg/dose'),
(123,'beclometasona (dipropionato de beclometasona)','cápsula inalante 200 mcg/dose'),
(124,'beclometasona (dipropionato de beclometasona)','solução para inalação oral 250 mcg/dose'),
(125,'beclometasona (dipropionato de beclometasona)','pó para inalação oral 400 mcg/dose'),
(126,'beclometasona (dipropionato de beclometasona)','cápsula inalante 400mcg/dose'),
(127,'bedaquilina','comprimido 100mg'),
(128,'benzilpenicilina benzatina','injetável, 600.000 UI frasco-ampola'),
(129,'benzilpenicilina benzatina','injetável, 1.200.000 UI frasco-ampola'),
(130,'benzilpenicilina potássica','injetável, 5.000.000 UI frasco-ampola'),
(131,'benzilpenicilina procaína + benzilpenicilina potássica','injetável, (300.000 + 100.000)UI frasco- ampola'),
(132,'benznidazol','comprimido 12,5 mg'),
(133,'benznidazol','comprimido 100 mg'),
(134,'beractanto (surfactante pulmonar)','suspensão injetável
intratecal ou intrabrônquica, 25 mg/mL frasco ampola'),
(135,'betainterferona 1a','injetável, 6.000.000 UI
(22 mcg) seringa preenchida'),
(136,'betainterferona 1a','injetável, 6.000.000 UI
(30 mcg) frasco ampola, seringa preenchida ou caneta preenchida'),
(137,'betainterferona 1a','injetável, 12.000.000 UI
(44 mcg) seringa preenchida'),
(138,'betainterferona 1b','injetável, 9.600.000 UI (300mcg) frasco ampola'),
(139,'betametasona (acetato
de betametasona  + fosfato dissódico de betametasona)','injetável, (3 mg + 3 mg)/mL ampola'),
(140,'bezafibrato','comprimido 200 mg'),
(141,'bezafibrato','comprimido de
desintegração lenta 400 mg  *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá
aguardar finalização de'),
(142,'bicarbonato de sódio','injetável, 1 mEq/mL
(8,4%) ampola'),
(143,'biotina','cápsula 2,5mg* item indisponível: Consta na RENAME, porém ainda não
disponibilizado pelo MS'),
(144,'bimatoprosta','solução oftálmica, 0,3mg/mL (0,03%)
frasco 3mL'),
(145,'biperideno (cloridrato de biperideno)','comprimido 2 mg'),
(146,'biperideno (cloridrato de biperideno)','comprimido de liberação controlada 4 mg'),
(147,'biperideno (lactato de biperideno)','injetável, 5 mg/mL ampola'),
(148,'bosentana','comprimido revestido 62,5 mg'),
(149,'bosentana','comprimido revestido 125mg'),
(150,'brimonidina','solução oftálmica, 2 mg/mL frasco com 5mL'),
(151,'brinzolamida','solução oftálmica, 10
mg/ml (0,01%) frasco
com 5 mL'),
(152,'bromocriptina','comprimido  2,5 mg *item indisponível no mercado nacional'),
(153,'budesonida','cápsula inalante ou pó inalante ou aerossol bucal 200 mcg'),
(154,'budesonida','cápsula inalante 400 mcg'),
(155,'budesonida','supensão para inalação nasal 32 mcg'),
(156,'budesonida','supensão para inalação nasal 50 mcg'),
(157,'budesonida','supensão para inalação nasal 64 mcg'),
(158,'bupivacaína (cloridrato de bupivacaína)','injetável, 2,5 mg/mL
(0,25%) ampola'),
(159,'bupivacaína (cloridrato de bupivacaína)','injetável, 5 mg/mL
(0,50%) ampola'),
(160,'bupropiona (cloridrato de bupropiona)','comprimidos de liberação prolongada 150 mg'),
(161,'cabergolina','comprimido 0,5 mg'),
(162,'calcipotriol','pomada, 50 mcg/g
(0,005%) bisnaga 30g'),
(163,'calcitonina','spray nasal, 200 UI/dose frasco'),
(164,'calcitriol','cápsula 0,25 mcg'),
(165,'caneta para aplicação de insulina','unidade'),
(166,'capreomicina','injetável, 1 g frasco- ampola'),
(167,'captopril','comprimido 25 mg'),
(168,'carbamazepina','comprimido 200 mg'),
(169,'carbamazepina','comprimido 400 mg'),
(170,'carbamazepina','suspensão oral, 20 mg/mL frasco'),
(171,'carbonato de cálcio','comprimido 1250mg (equivalente a 500 mg de cálcio)'),
(172,'carbonato de cálcio + colecalciferol','comprimido 1250 mg (500 mg de Ca) + 200 UI'),
(173,'carbonato de cálcio + colecalciferol','comprimido 1250 mg (500 mg de Ca) + 400 UI'),
(174,'carbonato de cálcio + colecalciferol','comprimido 1500 mg (600 mg de Ca) + 400 UI'),
(175,'carbonato de lítio','comprimido 300 mg'),
(176,'carvão vegetal ativado','pó para suspensão oral'),
(177,'cáscara-sagrada (Rhamnus purshiana DC. )','30  mg de derivados de hidroantracênicos
expressos em cascarosídeo A - dose'),
(178,'cefalexina','cápsula ou comprimido 500 mg'),
(179,'cefalexina','comprimido 500 mg'),
(180,'cefalexina','suspensão oral, 50 mg/mL frasco'),
(181,'cefalexina','suspensão oral, 50 mg/mL frasco'),
(182,'cefotaxima sódica','injetável, 500 mg frasco- ampola'),
(183,'ceftriaxona','injetável, 500 mg frasco ampola'),
(184,'ceftriaxona','injetável, 1 g frasco- ampola'),
(185,'certolizumabe pegol','injetável, 200 mg/mL seringa preenchida'),
(186,'cetoconazol','comprimido 200mg'),
(187,'cetoconazol','xampu, 20 mg/g (2%) frasco'),
(188,'cianocobalamina','injetável, 1000 mcg/mL ampola'),
(189,'ciclofosfamida','Comprimido 50 mg'),
(190,'ciclosporina','cápsula 10 mg'),
(191,'ciclosporina','cápsula 25 mg'),
(192,'ciclosporina','cápsula 50 mg'),
(193,'ciclosporina','cápsula 100 mg'),
(194,'ciclosporina','solução oral, 100 mg/ml frasco de 50 mL'),
(195,'ciclosporina','injetável, 50 mg frasco- ampola'),
(196,'ciclosporina','injetável, 250 mg frasco- ampola'),
(197,'cinacalcete','comprimidos 30 mg'),
(198,'cinacalcete','comprimidos 60 mg'),
(199,'ciprofibrato','comprimido 100 mg'),
(200,'ciprofloxacino','comprimido 250 mg'),
(201,'ciprofloxacino','comprimido 500 mg'),
(202,'ciproterona','comprimido 50 mg'),
(203,'claritromicina','comprimido 250 mg'),
(204,'claritromicina','comprimido 500 mg'),
(205,'claritromicina','suspensão oral,
50 mg/mL frasco'),
(206,'clindamicina (cloridrato de clindamicina)','cápsula 150 mg'),
(207,'clindamicina (cloridrato de clindamicina)','cápsula 300 mg'),
(208,'clindamicina (fosfato de clindamicina)','gel, 10mg/g'),
(209,'','solução tópica, 10mg/g'),
(210,'clobazam','comprimido 10 mg'),
(211,'clobazam','comprimido 20 mg'),
(212,'clobetasol','creme 0,5mg/g, bisnaga 30 g'),
(213,'clobetasol','solução capilar, 0,5
mg/g frasco 50g *item atualmente sem demanda nas farmácia cidadãs. Após abertura (fluxo NP) e deferimento do processo, seu
fornecimento deverá aguardar'),
(214,'clofazimina','cápsula 50 mg'),
(215,'clofazimina','cápsula 100 mg'),
(216,'clomifeno (citrato de clomifeno)','comprimido 50 mg *item
atualmente sem demanda nas farmácia cidadãs. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar finalização de processo'),
(217,'clomipramina (cloridrato de','comprimido 10 mg'),
(218,'clomipramina)','comprimido 25 mg'),
(219,'clonazepam','comprimido 0,5mg'),
(220,'clonazepam','comprimido 2mg'),
(221,'clonazepam','solução oral, 2,5 mg/mL frasco'),
(222,'clopidogrel','comprimido 75 mg'),
(223,'cloranfenicol','cápsula ou comprimido 250 mg'),
(224,'cloranfenicol','suspensão oral, 25 mg/mL frasco'),
(225,'cloreto de potássio','injetável, 2,56 mEq/mL
(19,1%) ampola'),
(226,'cloreto de sódio','injetável,  0,154
mEq/mL (0,9%) ampola'),
(227,'cloreto de sódio','solução nasal,  0,154
mEq/mL (0,9%) ampola'),
(228,'cloreto de sódio','injetável, 3,4 mEq/mL
(20%) ampola'),
(229,'cloreto de sódio','solução nasal, 9 mg/mL (0,9%) frasco'),
(230,'clorexidina (digliconato de clorexidina)','solução bucal, 0,12% frasco'),
(231,'clorexidina (digliconato de clorexidina)','solução para uso tópico, 2% a 4% frasco'),
(232,'clorexidina (digliconato de clorexidina)','solução degermante, 4% frasco com 100mL'),
(233,'cloroquina','comprimido 150mg
(correspondente a 250mg de Difosfato de cloroquina)*item atualmente sem demanda nas farmácia cidadãs. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá
aguardar finalização de'),
(234,'clorpromazina (cloridrato de clorpromazina)','comprimido 25 mg'),
(235,'clorpromazina (cloridrato de clorpromazina)','comprimido 100 mg'),
(236,'clorpromazina (cloridrato de clorpromazina)','injetável, 5 mg/mL ampola'),
(237,'clorpromazina (cloridrato de clorpromazina)','solução oral, 40 mg/mL frasco'),
(238,'clozapina','comprimido 25 mg'),
(239,'clozapina','comprimido 100 mg'),
(240,'codeína','comprimido 30 mg'),
(241,'codeína','comprimido 60 mg'),
(242,'codeína','solução oral, 3 mg/mL
frasco de 120 mL *item atualmente sem demanda nas farmácia cidadãs. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(243,'codeína','injetável, 30 mg/mL
ampola de 2 mL
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar finalização de'),
(244,'colecalciferol (vitamina D)','comprimido 7.000 UI'),
(245,'colimicina','pó para injeção
1.000.000 UI'),
(246,'alimentar p/ paciente fenilcetonurico menor de 1 ano - formula de aminoácidos isenta de','(por grama)'),
(247,'complemento alimentar p/ paciente fenilcetonurico maior de 1 ano - formula de aminoácidos isenta de fenilalanina','Pacientes 01 a 08 anos (por grama)'),
(248,'complemento alimentar p/ paciente fenilcetonurico maior de 1 ano - formula de aminoácidos isenta de fenilalanina','Pacientes maior de 08 anos (por grama)'),
(249,'complexo protrombínico humano','injetável, 500 a 600 UI frasco-ampola'),
(250,'complexo protrombínico parcialmente ativado','injetável, 500 UI frasco- ampola'),
(251,'complexo protrombínico parcialmente ativado','injetável, 1000 UI frasco- ampola'),
(252,'complexo protrombínico parcialmente ativado','injetável, 2500 UI frasco- ampola'),
(253,'dabigatrana (etexilato de dabigatrana)','cápsula 110 mg'),
(254,'dabigatrana (etexilato de dabigatrana)','cápsula 150 mg'),
(255,'daclatasvir','comprimido 30mg'),
(256,'daclatasvir','comprimido 60mg'),
(257,'daclizumabe','injetável, 5 mg/mL frasco'),
(258,'dactinomicina','injetável, 500 mcg/ml frascoampola'),
(259,'danazol','cápsula 100 mg'),
(260,'danazol','cápsula 200 mg'),
(261,'dapagliflozina','comprimido 10 mg'),
(262,'dapsona','comprimido 50mg*
(Disponível apenas no blíster da  poliquimioterapia Única – PQT-U, com outros medicamentos, para o esquema'),
(263,'dapsona','comprimido 100mg*
(Disponível apenas no blíster da  poliquimioterapia Única – PQT-U, com outros medicamentos, para o esquema'),
(264,'dapsona','comprimido 100 mg'),
(265,'darunavir','comprimido 75 mg'),
(266,'darunavir','comprimido 600 mg'),
(267,'dasatinibe','comprimido 20 mg'),
(268,'dasatinibe','comprimido 100 mg'),
(269,'deferasirox','comprimido 125 mg'),
(270,'deferasirox','comprimido 250 mg'),
(271,'deferasirox','comprimido 500 mg'),
(272,'deferiprona','comprimido 500 mg'),
(273,'delamanida','comprimido 500 mg'),
(274,'desferroxamina','injetável, 500 mg frasco ampola'),
(275,'desmopressina (acetato de desmopressina)','injetável, 4 mcg/mL ampola'),
(276,'desmopressina (acetato de desmopressina)','injetável, 15 mcg/mL ampola'),
(277,'desmopressina (acetato de desmopressina)','comprimido 0,1  mg* item indisponível: Consta na RENAME, porém ainda não disponibilizado pelo MS'),
(278,'desmopressina (acetato de desmopressina)','comprimido 0,2  mg* item indisponível: Consta na RENAME, porém ainda não disponibilizado pelo MS'),
(279,'desmopressina (acetato de desmopressina)','aplicação nasal, 0,1 mg/mL  frasco de 2,5 mL'),
(280,'dexametasona','comprimido 4 mg'),
(281,'dexametasona','creme 1 mg/g (0,1%)'),
(282,'dexametasona','elixir, 0,1 mg/mL frasco'),
(283,'dexametasona','pomada oftálmica, 1
mg/mL (0,1%)'),
(284,'dexametasona','suspensão oftálmica, 1
mg/mL (0,1%)'),
(285,'dexametasona (fosfato dissódico de dexametasona)','injetável, 4 mg/mL ampola'),
(286,'dexclorfeniramina (maleato de dexclorfeniramina)','comprimido 2 mg'),
(287,'dexclorfeniramina (maleato de dexclorfeniramina)','solução oral, 0,4 mg/mL frasco'),
(288,'dexclorfeniramina (maleato de dexclorfeniramina)','xarope, 0,4 mg/mL frasco'),
(289,'diafragma','60 mm de diâmetro'),
(290,'diafragma','65 mm de diâmetro'),
(291,'diafragma','70 mm de diâmetro'),
(292,'diafragma','75 mm de diâmetro'),
(293,'diafragma','80 mm de diâmetro'),
(294,'diafragma','85 mm de diâmetro'),
(295,'diazepam','comprimido 5 mg'),
(296,'diazepam','comprimido 10 mg'),
(297,'diazepam','comprimido 10 mg'),
(298,'diazepam','injetável, 5 mg/mL ampola'),
(299,'dietilcarbamazepina (citrato de dietilcarbamazepina)','comprimido 50mg'),
(300,'digoxina','comprimido 0,25 mg'),
(301,'digoxina','elixir, 0,05 mg/mL frasco'),
(302,'dipirona','comprimido 500 mg'),
(303,'dipirona','injetável, 500mg/mL frasco'),
(304,'dipirona','solução oral, 500 mg/mL frasco'),
(305,'dispositivo intra- uterino plástico com cobre','modelo T 380 mm2'),
(306,'dobutamina (cloridrato de dobutamina)','injetável, 12,5 mg/mL ampola'),
(307,'dolutegravir sódio','comprimido 50 mg'),
(308,'domperidona','suspensão oral, 1mg/mL frasco'),
(309,'donepezila','comprimido 5 mg'),
(310,'donepezila','comprimido 10 mg'),
(311,'dopamina (cloridrato de dopamina)','injetável, 5 mg/mL ampola'),
(312,'dorzolamida','solução oftálmica, 20 mg/mL frasco com 5mL'),
(313,'doxazosina (mesilato de doxazosina)','comprimido 2 mg'),
(314,'doxazosina (mesilato de doxazosina)','comprimido 4 mg'),
(315,'doxiciclina','comprimido 100 mg'),
(316,'doxiciclina','injetável, 100 mg frasco- ampola'),
(317,'efavirenz','cápsula 200 mg'),
(318,'efavirenz','comprimido 600 mg'),
(319,'efavirenz','solução oral, 30 mg/mL frasco'),
(320,'elbasvir + grazoprevir monoidratado','comprimido, 50mg + 100mg'),
(321,'eltrombopague olamina','comprimido 25 mg'),
(322,'eltrombopague olamina','comprimido 50 mg'),
(323,'enalapril (maleato de enalapril)','comprimido 5 mg'),
(324,'enalapril (maleato de enalapril)','comprimido 10 mg'),
(325,'enalapril (maleato de enalapril)','comprimido 20 mg'),
(326,'enfuvirtida','injetável, 108 mg (90 mg/ mL após reconstituição) frasco ampola'),
(327,'enoxaparina sódica','injetável, 20 mg/0,2mL seringa preenchida'),
(328,'enoxaparina sódica','injetável, 40 mg/0,4mL seringa preenchida'),
(329,'enoxaparina sódica','injetável, 60 mg/0,6mL seringa preenchida'),
(330,'enoxaparina sódica','injetável, 80 mg/0,8mL seringa preenchida'),
(331,'enoxaparina sódica','injetável, 100 mg/1mL seringa preenchida'),
(332,'entacapona','comprimido 200 mg'),
(333,'entecavir','comprimido 0,5 mg'),
(334,'entecavir','comprimido 1 mg'),
(335,'epinefrina','injetável, 1 mg/mL ampola'),
(336,'eritromicina (estolato de eritromicina)','comprimido 500 mg'),
(337,'eritromicina (estolato de eritromicina)','comprimido 500 mg'),
(338,'eritromicina (estolato de eritromicina)','suspensão oral, 25 mg/mL frasco'),
(339,'eritromicina (estolato de eritromicina)','suspensão oral, 50 mg/mL frasco'),
(340,'eritromicina (estolato de eritromicina)','suspensão oral, 50 mg/mL frasco'),
(341,'espinheira-santa (Maytenus ilicifolia Mart. ex Reissek )','cápsula, emulsão oral,
solução oral e tintura (60 a 90mg de taninos totais expressos em pirogalol - dose diária)'),
(342,'espiramicina','comprimido 1,5 MUI'),
(343,'espironolactona','comprimido 25 mg'),
(344,'espironolactona','comprimido 100 mg'),
(345,'estreptomicina (sulfato de estreptomicina)','injetável, 1 g frasco- ampola'),
(346,'estreptoquinase','injetável, 250.000 UI frasco ampola'),
(347,'estriol','creme vaginal 1 mg/g'),
(348,'estrogênios conjugados','comprimido 0,3 mg'),
(349,'estrogênios conjugados','creme vaginal 0,625 mg/g'),
(350,'etambutol (cloridrato de etambutol)','comprimido 400 mg'),
(351,'etanercepte','injetável, 25 mg frasco ampola'),
(352,'etanercepte','injetável, 50 mg frasco ampola ou seringa preenchida'),
(353,'etinilestradiol + levonorgestrel','comprimido 0,03 + 0,15mg'),
(354,'etionamida','comprimido 250 mg'),
(355,'etofibrato','cápsula 500 mg
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo,
seu fornecimento deverá
aguardar finalização de'),
(356,'etossuximida','Solução oral, 50 mg/mL frasco com 120 mL'),
(357,'etravirina','comprimido 100 mg'),
(358,'etravirina','comprimido 200 mg'),
(359,'everolimo','comprimido 0,5 mg'),
(360,'everolimo','comprimido 0,75 mg'),
(361,'everolimo','comprimido 1 mg'),
(362,'fator VII ativado recombinante (alfaeptacogue ativado)','injetável, 1 mg (50.000UI) frasco-ampola'),
(363,'fator VII ativado recombinante (alfaeptacogue ativado)','injetável, 2 mg (100.000UI) frasco- ampola'),
(364,'fator VII ativado recombinante (alfaeptacogue ativado)','injetável, 5 mg (250.000UI) frasco- ampola'),
(365,'fator VIII de coagulação','injetável, 250 UI frasco- ampola'),
(366,'fator VIII de coagulação','injetável, 500 UI frasco- ampola'),
(367,'fator VIII de coagulação','injetável, 1.000 UI frasco-ampola'),
(368,'fator VIII recombinante (alfaoctocogue)','injetável, 250 UI frasco- ampola'),
(369,'fator VIII recombinante (alfaoctocogue)','injetável, 500 UI frasco- ampola'),
(370,'fator VIII recombinante (alfaoctocogue)','injetável, 1000 UI frasco- ampola'),
(371,'fator VIII de coagulação contendo Fator doença de von Willebrand','injetável, 250 UI frasco- ampola'),
(372,'fator VIII de coagulação contendo Fator doença de von Willebrand','injetável, 500 UI frasco- ampola'),
(373,'fator VIII de coagulação contendo Fator doença de von Willebrand','injetável, 1000 UI frasco- ampola'),
(374,'fator IX de coagulação','injetável, 200 UI frasco- ampola'),
(375,'fator IX de coagulação','injetável, 250 UI frasco- ampola'),
(376,'fator IX de coagulação','injetável, 500 UI frasco- ampola'),
(377,'fator IX de coagulação','injetável, 600 UI frasco- ampola'),
(378,'fator IX de coagulação','injetável, 1.000 UI frasco-ampola'),
(379,'fator IX de coagulação','injetável, 1.200 UI frasco-ampola'),
(380,'fator XIII de coagulação','injetável, 250 UI frasco- ampola'),
(381,'fenitoína sódica','comprimido 100 mg'),
(382,'fenitoína sódica','injetável, 50 mg/mL ampola'),
(383,'fenitoína sódica','suspensão oral,
20 mg/mL frasco'),
(384,'fenobarbital','comprimido 100 mg'),
(385,'fenobarbital','injetável, 100 mg/mL ampola'),
(386,'fenobarbital','solução oral, 40 mg/mL frasco'),
(387,'fenofibrato','cápsula 200 mg'),
(388,'fenofibrato','cápsula de liberação retardada 250 mg'),
(389,'fenoterol','aerossol, 100 mcg/dose -
frasco com 200 doses
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar finalização de processo licitatório.'),
(390,'fenoximetilpenicilina potássica','pó para solução oral,
80.000 UI/mL'),
(391,'fibrinogênio','injetável, 1 g frasco- ampola'),
(392,'filgrastim','injetável, 300 mcg frasco-ampola ou seringa preenchida'),
(393,'finasterida','comprimido 5 mg'),
(394,'fingolimode','cápsula 0,5 mg'),
(395,'flucitosina','cápsula 250 mg'),
(396,'flucitosina','cápsula 500mg'),
(397,'fluconazol','cápsula 100 mg'),
(398,'fluconazol','cápsula 150 mg'),
(399,'fluconazol','injetável, 2 mg/mL ampola'),
(400,'fluconazol','suspensão oral, 10 mg/mL frasco'),
(401,'fludrocortisona','comprimido 0,1 mg'),
(402,'flumazenil','injetável, 0,1 mg/mL ampola'),
(403,'fluoxetina (cloridrato de fluoxetina)','cápsula ou comprimido 20 mg'),
(404,'formoterol','cápsula inalante ou pó inalante 12 mcg'),
(405,'formoterol + budesonida','cápsula inalante ou pó inalante, 6 + 200 mcg'),
(406,'formoterol + budesonida','cápsula inalante ou pó inalante, 12 + 400 mcg'),
(407,'fosamprenavir','suspensão oral 50 mg/mL'),
(408,'fosfato de cálcio tribásico + colecalciferol','comprimido 1661,616mg (600mg de cálcio) + 400 UI'),
(409,'fosfato de potássio monobásico + fostato de potássio dibásico','injetável, 0,03 + 0,1567 g/mL ampola'),
(410,'Denominação genérica','Forma Farmacêutica / Concentração / Descrição'),
(411,'Fósforo Elementar','comprimido, 250 mg de fósforo elementar*
Formulação manipulada - composição conforme tabela 2 PCDT'),
(412,'Fósforo Elementar','Solução Fosfatada, 15mg de fósforo elementar/mL de solução* Formulação manipulada - composição conforme tabela 1 PCDT'),
(413,'fumarato de Dimetila','cápsula 120 mg'),
(414,'fumarato de Dimetila','cápsula 240 mg'),
(415,'furosemida','comprimido 40 mg'),
(416,'furosemida','injetável, 10 mg/mL ampola'),
(417,'gabapentina','cápsula 300 mg'),
(418,'gabapentina','cápsula 400 mg'),
(419,'ganciclovir sódico','injetável, 1 mg/mL bolsa 250mL sistema fechado'),
(420,'galantamina','cápsula de liberação prolongada 8 mg'),
(421,'galantamina','cápsula de liberação prolongada 16 mg'),
(422,'galantamina','cápsula de liberação prolongada 24 mg'),
(423,'galsulfase','injetável, 5 mg Frasco'),
(424,'garra-do-diabo (Harpagophytum procumbens DC. Ex Meissn. )','cápsula, comprimido e
comprimido de liberação retardada (30 a 100mg de harpagosídeo ou 45 a 150mg de irodoides totais expressos em harpagosídeos - dose'),
(425,'gel lubrificante','gel'),
(426,'genfibrozila','comprimido 600 mg'),
(427,'genfibrozila','comprimido 900 mg *item atualmente sem demanda.
Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(428,'gentamicina (sulfato de gentamicina)','pomada oftálmica
5 mg/g'),
(429,'gentamicina (sulfato de gentamicina)','solução oftálmica, 5 mg/mL frasco'),
(430,'glatirâmer','injetável, 20 mg  seringa preenchida'),
(431,'glatirâmer','injetável, 40 mg seringa preenchida'),
(432,'glecaprevir + pibrentasvir','comprimido, 100mg + 40mg'),
(433,'glibenclamida','comprimido 5 mg'),
(434,'glicerol','solução retal, 120 mg/mL frasco'),
(435,'glicerol','supositório retal 72 mg'),
(436,'gliclazida','comprimido de liberação prolongada 30 mg'),
(437,'gliclazida','comprimido de liberação prolongada  60 mg'),
(438,'gliclazida','comprimido 80 mg'),
(439,'glicose','injetável, 50 mg/mL
(5%) ampola'),
(440,'glicose','injetável, 100 mg/mL
(10%) ampola'),
(441,'glicose','injetável, 500 mg/mL
(50%) ampola'),
(442,'glutaral','solução 2%'),
(443,'golimumabe','injetável, 50 mg seringa preenchida'),
(444,'gosserrelina','injetável, 3,60 mg seringa preenchida'),
(445,'gosserrelina','injetável, 10,80 mg seringa preenchida'),
(446,'guaco (Mikania glomerata Spreng. )','solução oral, tintura e xarope (0,5 a 5mg de cumarina - dose diária)'),
(447,'haloperidol','comprimido 1 mg'),
(448,'haloperidol','comprimido 5 mg'),
(449,'haloperidol','injetável, 5 mg/mL ampola'),
(450,'haloperidol','solução oral, 2 mg/mL frasco'),
(451,'haloperidol (decanoato de haloperidol)','injetável, 50 mg/mL ampola'),
(452,'hemitartarato de norepinefrina','injetável, 2 mg/mL ampola'),
(453,'heparina sódica','injetável, 5.000 UI/0,25 mL ampola'),
(454,'hidralazina (cloridrato de hidralazina)','comprimido 25 mg'),
(455,'hidralazina (cloridrato de hidralazina)','comprimido 50 mg'),
(456,'hidroclorotiazida','comprimido 12,5 mg'),
(457,'hidroclorotiazida','comprimido 25 mg'),
(458,'hidrocortisona (acetato de hidrocortisona)','creme 10 mg/g (1%)'),
(459,'hidrocortisona (succinato sódico de hidrocortisona)','injetável, 100 mg frasco- ampola'),
(460,'hidrocortisona (succinato sódico de hidrocortisona)','injetável, 500 mg frasco- ampola'),
(461,'hidroxicloroquina','comprimido 400 mg'),
(462,'hidroxiureia','cápsula 500 mg'),
(463,'hidroxocobalamina (cloridrato de hidroxocobalamina)','injetável, 5 g frasco- ampola'),
(464,'hipoclorito de sódio','solução, 10 mg/mL (1%) frasco'),
(465,'hipoclorito de sódio','solução, 25 mg/mL
(2,5%) frasco'),
(466,'hipromelose','solução oftálmica, 3
mg/mL (0,3%) frasco'),
(467,'hipromelose','solução oftálmica, 5
mg/mL (0,5%) frasco'),
(468,'hortelã (Mentha x piperita L .)','cápsula (60 a 440 mg de mentol e 28 a 256 mg de mentona - dose diária)'),
(469,'ibuprofeno','comprimido 200 mg'),
(470,'ibuprofeno','comprimido 300 mg'),
(471,'ibuprofeno','comprimido 600 mg'),
(472,'ibuprofeno','suspensão oral, 50 mg/mL frasco'),
(473,'icatibanto (acetato de icatibanto)','injetável, 10 mg/mL seringa preenchida 3mL'),
(474,'idursulfase','injetável, 2 mg/ml frasco ampola 3mL'),
(475,'iloprosta','solução para
nebulização, 10 mcg/mL ampola 1 ml *item atualmente sem demanda.
Após abertura (fluxo NP)e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(476,'imatinibe (mesilato de imatinibe)','comprimido 100 mg'),
(477,'imatinibe (mesilato de imatinibe)','comprimido 400 mg'),
(478,'imiglucerase','injetável, 400 UI frasco ampola'),
(479,'imiquimode','creme, 50mg/g'),
(480,'imunoglobulina anti RH (D)','injetável'),
(481,'imunoglobulina humana antirrábica','injetável, 150 UI/mL ampola'),
(482,'imunoglobulina antitetânica','injetável, 250 UI/mL ampola'),
(483,'imunoglobulina antivaricela zoster','injetável, 125 UI/2,5 ml ampola'),
(484,'imunoglobulina','injetável, 0,5 g frasco
*item atualmente sem demanda. Após abertura (fluxo NP)e deferimento do processo, seu fornecimento deverá aguardar finalização de processo licitatório.'),
(485,'imunoglobulina','injetável, 1,0 g frasco
*item atualmente sem demanda. Após abertura (fluxo NP)e deferimento do processo, seu fornecimento deverá aguardar finalização de processo licitatório.'),
(486,'imunoglobulina antitimócitos humanos (coelho)','injetável, 25 mg frasco ampola'),
(487,'imunoglobulina humana anti-hepatite B','injetável, 100 UI ampola  '),
(488,'imunoglobulina humana anti-hepatite B','injetável, 180 a 200 UI/mL ampola'),
(489,'imunoglobulina humana anti-hepatite B','injetável, 500 UI ampola  '),
(490,'imunoglobulina humana anti-hepatite B','injetável, 600 UI ampola  '),
(491,'imunoglobulina humana anti-hepatite B','injetável, 1000 UI ampola  '),
(492,'infliximabe','injetável, 100mg frasco- ampola'),
(493,'insulina análoga de ação rápida (insulina Asparte)','injetável, 100 UI/mL caneta com 3mL + agulha 0,23 x 4mm'),
(494,'insulina humana de ação rápida (insulina regular)','injetável, 100 UI/mL frasco-ampola'),
(495,'insulina humana de duração intermediária (insulina NPH)','injetável, 100 UI/mL frasco-ampola'),
(496,'insulina análoga de longa duração (insulina detemir)','injetável, 100 UI/mL refil ou caneta com 3mL'),
(497,'insulina análoga de longa duração (insulina glargina)','injetável, 100 UI/mL frasco ampola 10mL'),
(498,'insulina análoga de longa duração (insulina glargina)','injetável, 100 UI/mL refil com 3mL'),
(499,'iodo + iodeto de potássio','solução, (20 + 40) mg/mL frasco'),
(500,'ipratrópio (brometo de ipratrópio)','solução para inalação oral 20 mcg/dose'),
(501,'ipratrópio (brometo de ipratrópio)','solução para inalação 0,25 mg/mL'),
(502,'isoflavona-de-soja [Glycine max  (L. ) Merr. ]','cápsula ou comprimido (50 a 120 mg de isoflavonas - dose diária)'),
(503,'isoniazida','comprimido 100 mg'),
(504,'isoniazida','comprimido 300 mg'),
(505,'isossorbida (dinitrato de isossorbida)','comprimido sublingual 5mg'),
(506,'isossorbida (mononitrato de isossorbida)','comprimido 20 mg'),
(507,'isossorbida (mononitrato de isossorbida)','comprimido 40 mg'),
(508,'isotretinoína','cápsula 10 mg'),
(509,'isotretinoína','cápsula 20 mg'),
(510,'itraconazol','cápsula 100 mg'),
(511,'itraconazol','solução oral, 10 mg/mL frasco'),
(512,'Ivacaftor','comprimido 150mg'),
(513,'ivermectina','comprimido 6 mg'),
(514,'lactulose','xarope, 667 mg/ mL frasco'),
(515,'lamivudina','comprimido 150 mg'),
(516,'lamivudina','solução oral, 10 mg/mL frasco'),
(517,'lamotrigina','comprimido 25 mg'),
(518,'lamotrigina','comprimido 50 mg'),
(519,'lamotrigina','comprimido 100 mg'),
(520,'lancetas para punção digital','unidade'),
(521,'lanreotida','injetável, 60 mg seringa preenchida'),
(522,'lanreotida','injetável, 90 mg seringa preenchida'),
(523,'lanreotida','injetável, 120 mg seringa preenchida'),
(524,'l-asparaginase','injetável, 10.000 UI frasco ampola'),
(525,'laronidase','injetável, 0,58 mg/mL
frasco com 5 mL* item indisponível: Consta na RENAME, porém ainda não
disponibilizado pelo MS'),
(526,'latanoprosta','solução oftálmica, 0,05mg/mL frasco 2,5mL'),
(527,'ledipasvir + sofosbuvir','comprimido (90 + 400)mg'),
(528,'leflunomida','comprimido 20 mg'),
(529,'leuprorrelina','injetável, 3,75 mg frasco ampola'),
(530,'leuprorrelina','injetável, 11,25 mg frasco ampola'),
(531,'leuprorrelina','injetável,  45 mg frasco ampola'),
(532,'levetiracetam','solução oral, 100mg/mL frasco 100 ou 150mL'),
(533,'levetiracetam','comprimido 250mg'),
(534,'levetiracetam','comprimido 750mg'),
(535,'levodopa + benserazida','cápsula ou comprimido 100 mg + 25 mg'),
(536,'levodopa + benserazida','comprimido 200 mg + 50 mg'),
(537,'levodopa + carbidopa','comprimido 200 mg + 50 mg'),
(538,'levodopa + carbidopa','comprimido 250 mg + 25 mg'),
(539,'levofloxacino','comprimido 250 mg'),
(540,'levofloxacino','comprimido 500 mg'),
(541,'levonorgestrel','comprimido 1,5 mg'),
(542,'levonorgestrel','comprimido 0,75 mg'),
(543,'levotiroxina sódica','comprimido 12,5 mcg'),
(544,'levotiroxina sódica','comprimido 25 mcg'),
(545,'levotiroxina sódica','comprimido 37,5 mcg'),
(546,'levotiroxina sódica','comprimido 50 mcg'),
(547,'levotiroxina sódica','comprimido 100 mcg'),
(548,'lidocaína (cloridrato de lidocaína)','injetável, 10 mg/mL
(1%) ampola'),
(549,'lidocaína (cloridrato de lidocaína)','injetável, 20 mg/mL
(2%) ampola'),
(550,'lidocaína (cloridrato de lidocaína)','gel 20 mg/mL (2%)'),
(551,'lidocaína (cloridrato de lidocaína)','solução spray, 100 mg/mL frasco'),
(552,'lidocaína (cloridrato de lidocaína) + glicose','injetável, 50 + 75
mg/mL   (5 + 7,5%) ampola'),
(553,'lidocaína (cloridrato de lidocaína) + hemitartarato de epinefrina','injetável, 1% +
1:200.000 ampola'),
(554,'lidocaína (cloridrato de lidocaína) + hemitartarato de epinefrina','injetável, 2% +
1:80.000 ampola'),
(555,'lidocaína (cloridrato de lidocaína) + hemitartarato de epinefrina','injetável, 2% +
1:200.000 ampola'),
(556,'linezolida','comprimido 600 mg'),
(557,'linezolida','solução para infusão, 2 mg/mL frasco'),
(558,'lopinavir + ritonavir','comprimido 100 mg + 25mg'),
(559,'lopinavir + ritonavir','comprimido 200 mg + 50mg'),
(560,'lopinavir + ritonavir','solução oral, 80 mg/mL
+ 20 mg/mL frasco'),
(561,'loratadina','comprimido 10 mg'),
(562,'loratadina','xarope, 1 mg/mL frasco'),
(563,'losartana potássica','comprimido 50 mg'),
(564,'maraviroque','comprimido 150 mg'),
(565,'medicamento homeopáticos','conforme Farmacopéia Homeopática Brasileira 3ª edição'),
(566,'medroxiprogesterona (acetato de medroxiprogesterona)','comprimido 10 mg'),
(567,'medroxiprogesterona (acetato de medroxiprogesterona)','injetável, 50 mg/mL ampola'),
(568,'medroxiprogesterona (acetato de medroxiprogesterona)','injetável, 150 mg/mL ampola'),
(569,'memantina','comprimido 10 mg'),
(570,'mepolizumabe','solução injetável, 100mg frasco ampola'),
(571,'mesalazina','comprimido 400 mg'),
(572,'mesalazina','comprimido de liberação prolongada 500 mg'),
(573,'mesalazina','comprimido 800 mg'),
(574,'mesalazina','enema retal, 10 mg/mL frasco com 100 mL'),
(575,'mesalazina','supositório 250 mg'),
(576,'mesalazina','supositório 500 mg'),
(577,'mesalazina','supositório 1000 mg'),
(578,'metadona','comprimido 5 mg'),
(579,'metadona','comprimido 10 mg'),
(580,'metadona','injetável, 10 mg/mL
ampola 1 mL
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo,
seu fornecimento deverá
aguardar finalização de'),
(581,'metformina (cloridrato de metformina)','comprimido 500 mg'),
(582,'metformina (cloridrato de metformina)','comprimido 850 mg'),
(583,'metildopa','comprimido 250 mg'),
(584,'metilfenidato','comprimido de liberação imediata 10 mg'),
(585,'metilfenidato','comprimido de liberação prolongada 20 mg'),
(586,'metilfenidato','comprimido de liberação prolongada 30 mg'),
(587,'metilfenidato','comprimido de liberação prolongada 40 mg'),
(588,'metilprednisolona','injetável, 500 mg frasco ampola'),
(589,'metoclopramida (cloridrato de metoclopramida)','comprimido 10 mg'),
(590,'metoclopramida (cloridrato de metoclopramida)','injetável, 5 mg/mL ampola'),
(591,'metoclopramida (cloridrato de metoclopramida)','solução oral, 4 mg/mL frasco'),
(592,'metoprolol (succinato de metoprolol)','comprimido de liberação prolongada 25 mg'),
(593,'metoprolol (succinato de metoprolol)','comprimido de liberação prolongada 50 mg'),
(594,'metoprolol (succinato de metoprolol)','comprimido de liberação prolongada 100 mg'),
(595,'metoprolol (tartarato de metoprolol)','comprimido 100 mg'),
(596,'metotrexato','comprimido 2,5 mg'),
(597,'metotrexato','injetável, 25 mg/mL ampola de 2 mL'),
(598,'metronidazol','comprimido 250 mg'),
(599,'metronidazol','comprimido 250 mg'),
(600,'metronidazol','comprimido 400 mg'),
(601,'metronidazol','gel vaginal 100 mg/g (10%)'),
(602,'metronidazol','gel vaginal 100 mg/g (10%)'),
(603,'metronidazol (benzoilmetronidazol)','suspensão oral 40 mg/mL'),
(604,'micofenolato de mofetila','comprimido 500 mg'),
(605,'micofenolato de sodio','comprimido 180 mg'),
(606,'micofenolato de sodio','comprimido 360 mg'),
(607,'miconazol (nitrato de miconazol)','creme 20 mg/g (2%)'),
(608,'miconazol (nitrato de miconazol)','gel oral 20 mg/g (2%)'),
(609,'micronutrientes','pó, 1 g (vitamina A 400 mcg + vitamina D 5 mcg, vitamina E 5 mgvitamina C 30 mg,
vitamina B1 0,5 mg,'),
(610,'midazolam (maleato de midazolam)','comprimido 15 mg'),
(611,'midazolam (maleato de midazolam)','solução oral, 2 mg/mL frasco'),
(612,'miglustate','cápsula 100 mg'),
(613,'miltefosina','cápsula 10 mg'),
(614,'miltefosina','cápsula 50 mg'),
(615,'minociclina (cloridrato de minociclina)','comprimido 100 mg'),
(616,'misoprostol','comprimido vaginal 25mcg'),
(617,'misoprostol','comprimido vaginal 200mcg'),
(618,'mometasona','suspensão nasal, spray 50 mcg frasco com 120 atomizações'),
(619,'montelucaste de sódio','grânulos orais 4 mg'),
(620,'montelucaste de sódio','comprimido mastigável 4mg'),
(621,'montelucaste de sódio','comprimido mastigável 5mg'),
(622,'montelucaste de sódio','comprimido revestido 10mg'),
(623,'morfina','cápsula de liberação controlada 30 mg'),
(624,'morfina','cápsula de liberação controlada 60 mg'),
(625,'morfina','cápsula de liberação
controlada 100 mg *item atualmente sem demanda nas farmácia cidadãs. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(626,'morfina','comprimido 10 mg'),
(627,'morfina','comprimido 30 mg'),
(628,'morfina','injetável, 10 mg/mL
ampola de 1 mL
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar finalização de'),
(629,'morfina','solução oral, 10 mg/mL
frasco de 60 mL    *item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo, seu fornecimento deverá aguardar
finalização de processo'),
(630,'moxifloxacino (cloridrato de moxifloxacino)','comprimido 400 mg'),
(631,'multivitaminas lipossolúveis e minerais','solução oral, frasco (até 2 anos)'),
(632,'multivitaminas lipossolúveis e minerais','comprimido mastigáveis (2 a 10 anos)'),
(633,'multivitaminas lipossolúveis e minerais','cápsulas gelatinosas (acima de 10 anos)'),
(634,'mupirocina','pomada, 2% tubo com 15g'),
(635,'naloxona (cloridrato de naloxona)','injetável, 0,4 mg/mL ampola'),
(636,'naproxeno','Comprimido 250mg'),
(637,'naproxeno','Comprimido 500mg'),
(638,'natalizumabe','injetável, 20 mg/mL frasco ampola com 15 mL'),
(639,'nevirapina','comprimido 200 mg'),
(640,'nevirapina','suspensão oral 10 mg/ mL'),
(641,'nicotina','adesivo transdérmico 7 mg'),
(642,'nicotina','adesivo transdérmico
14 mg'),
(643,'nicotina','adesivo transdérmico
21 mg'),
(644,'nicotina','goma de mascar 2 mg'),
(645,'nicotina','pastilha 2 mg'),
(646,'nifedipino','cápsula ou comprimido 10 mg'),
(647,'nilotinibe','comprimido 200 mg'),
(648,'nistatina','suspensão oral,
100.000 UI/mL frasco'),
(649,'','suspensão oral,
100.000 UI/mL frasco'),
(650,'nitrofurantoína','cápsula 100 mg'),
(651,'','suspensão oral, 5 mg/mL frasco'),
(652,'noretisterona','comprimido 0,35 mg'),
(653,'noretisterona
(enantato de noretisterona) + estradiol (valerato de estradiol)','injetável, 50 + 5 mg/mL ampola'),
(654,'nortriptilina (cloridrato de nortriptilina)','cápsula 10 mg'),
(655,'nortriptilina (cloridrato de nortriptilina)','cápsula 25 mg'),
(656,'nortriptilina (cloridrato de nortriptilina)','cápsula 50 mg'),
(657,'nortriptilina (cloridrato de nortriptilina)','cápsula 75 mg'),
(658,'nusinersena','injetável, 2,4 mg/mL frasco-ampola com 5 mL'),
(659,'Octreotida','injetável, 0,1 mg/mL ampola com 1 mL'),
(660,'Octreotida','injetável, 10 mg frasco-
ampola *item atualmente sem demanda. Após abertura (fluxo NP)e deferimento do processo, seu fornecimento
deverá aguardar finalização de'),
(661,'Octreotida','injetável, 20 mg frasco- ampola'),
(662,'Octreotida','injetável, 30 mg frasco- ampola'),
(663,'ofloxacino','comprimido 400 mg'),
(664,'olanzapina','comprimido 5 mg'),
(665,'olanzapina','comprimido 10 mg'),
(666,'óleo mineral','óleo para uso oral'),
(667,'omalizumabe','injetável, 150 mg frasco ampola'),
(668,'omeprazol','cápsula 10 mg'),
(669,'omeprazol','cápsula 20 mg'),
(670,'omeprazol','comprimido 20 mg'),
(671,'omeprazol magnésico','comprimido dispersível 10 mg'),
(672,'ondansetrona (cloridrato de ondansetrona)','comprimido 4 mg'),
(673,'ondansetrona (cloridrato de ondansetrona)','comprimido orodispersível 4 mg'),
(674,'ondansetrona (cloridrato de ondansetrona)','comprimido 8 mg'),
(675,'ondansetrona (cloridrato de ondansetrona)','comprimido orodispersível 8 mg'),
(676,'oseltamivir (fosfato de oseltamivir)','cápsula 45 mg'),
(677,'oseltamivir (fosfato de oseltamivir)','cápsula 75 mg'),
(678,'oxamniquina','suspensão oral, 50 mg/mL frasco'),
(679,'oxibutinina (cloridrato de oxibutinina)','comprimido 5 mg'),
(680,'oxibutinina (cloridrato de oxibutinina)','comprimido 10mg liberação prolongada'),
(681,'palivizumabe','injetável, 50mg frasco ampola'),
(682,'palivizumabe','injetável, 100mg frasco ampola'),
(683,'pamidronato','injetável, 60 mg frasco ampola'),
(684,'pancreatina','cápsula 10.000UI'),
(685,'pancreatina','cápsula 25.000UI'),
(686,'paracetamol','comprimido 500 mg'),
(687,'paracetamol','solução oral, 200 mg/mL frasco'),
(688,'paricalcitol','injetável, 5 mcg/mL ampola com 1 mL'),
(689,'pasta dágua','pasta'),
(690,'penicilamina','cápsula 250 mg'),
(691,'pentamidina (isetionato de pentamidina)','injetável, 300 mg frasco- ampola'),
(692,'pentoxifilina','comprimido 400 mg'),
(693,'permanganato de potássio','comprimido para uso tópico 100 mg'),
(694,'permanganato de potássio','pó, 100 mg frasco'),
(695,'permetrina','loção 10 mg/g (1%)'),
(696,'permetrina','loção 50 mg/g (5%)'),
(697,'peróxido de benzoíla','gel 25 mg/g (2,5%)'),
(698,'peróxido de benzoíla','gel 50 mg/g (5%)'),
(699,'pertuzumabe','injetável, 420 mg Frasco'),
(700,'pilocarpina (cloridrato de pilocarpina)','solução oftálmica, 20
mg/mL (2%)  frasco'),
(701,'pirazinamida','comprimido dispersível 150 mg'),
(702,'pirazinamida','comprimido 500 mg'),
(703,'pirazinamida','solução oral, 30 mg/mL (3%) frasco'),
(704,'piridostigmina','comprimido 60 mg'),
(705,'piridoxina (cloridrato de piridoxina)','comprimido 40 mg'),
(706,'piridoxina (cloridrato de piridoxina)','comprimido 100 mg'),
(707,'pirimetamina','comprimido 25 mg'),
(708,'plantago (Plantago ovata Forssk .)','pó para dispersão oral (3 a 30 g - dose diária)'),
(709,'podofilina','solução para uso tópico 100 mg/mL (10%) a
250 mg/mL (25%)'),
(710,'podofilotoxina','creme, 1,5 mg/g'),
(711,'Polimixina +
neomicina + fluocinolona + lidocaína (sulfato de polimixina B + sulfato de neomicina +','solução otológica,
10.000 UI/mL + 3,50 mg/mL + 0,250 mg/mL
+ 20,0 mg/mL'),
(712,'polivitamínico','comprimidos'),
(713,'polivitamínico','solução oral (gotas)'),
(714,'pralidoxima (mesilato de pralidoxima)','injetável, 200 mg frasco- ampola'),
(715,'pramipexol (dicloridrato de pramipexol)','comprimido 0,125 mg'),
(716,'pramipexol (dicloridrato de pramipexol)','comprimido 0,25 mg'),
(717,'pramipexol (dicloridrato de pramipexol)','comprimido 1 mg'),
(718,'pravastatina','comprimido 10mg
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo,
seu fornecimento deverá
aguardar finalização de'),
(719,'pravastatina','comprimido 20mg
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo,
seu fornecimento deverá
aguardar finalização de'),
(720,'pravastatina','comprimido 40 mg
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo,
seu fornecimento deverá
aguardar finalização de'),
(721,'praziquantel','comprimido 600 mg'),
(722,'prednisolona (fosfato sódico de prednisolona)','solução oral, 1 mg/mL frasco'),
(723,'prednisolona (fosfato sódico de prednisolona)','solução oral, 3 mg/mL frasco'),
(724,'prednisona','comprimido 5 mg'),
(725,'prednisona','comprimido 20 mg'),
(726,'preservativo feminino','até 20 cm'),
(727,'preservativo masculino','160 mm x 49 mm'),
(728,'preservativo masculino','160 mm x 52 mm'),
(729,'prilocaína (cloridrato de prilocaína) + felipressina','injetável, 30 mg/mL
(3%) + 0,03 UI/mL
ampola'),
(730,'primaquina (difosfato de primaquina)','comprimido 5 mg'),
(731,'primaquina (difosfato de primaquina)','comprimido 15 mg'),
(732,'primidona','comprimido 100 mg'),
(733,'primidona','comprimido 250 mg
*item atualmente sem demanda. Após abertura (fluxo NP) e deferimento do processo,
seu fornecimento deverá
aguardar finalização de'),
(734,'prometazina (cloridrato de prometazina)','comprimido 25 mg'),
(735,'prometazina (cloridrato de prometazina)','injetável, 25 mg/mL ampola'),
(736,'propafenona (cloridrato de','comprimido 150 mg'),
(737,'propafenona)','comprimido 300 mg'),
(738,'propiltiouracila','comprimido 100 mg'),
(739,'propranolol (cloridrato de propranolol)','comprimido 10 mg'),
(740,'propranolol (cloridrato de propranolol)','comprimido 40 mg'),
(741,'protamina (cloridrato de protamina)','injetável, 10 mg/mL ampola'),
(742,'quetiapina','comprimido 25 mg'),
(743,'quetiapina','comprimido 100 mg'),
(744,'quetiapina','comprimido 200 mg'),
(745,'quetiapina','comprimido 300 mg'),
(746,'raloxifeno (cloridrato de raloxifeno)','comprimido 60 mg'),
(747,'raltegravir potássico','comprimido 100 mg'),
(748,'raltegravir potássico','comprimido 400 mg'),
(749,'ranitidina','xarope, 15 mg/mL frasco'),
(750,'rasagilina','comprimido 1 mg'),
(751,'retinol (palmitato de retinol)','cápsula mole 100.000 UI'),
(752,'retinol (palmitato de retinol)','cápsula mole 200.000 UI'),
(753,'retinol (palmitato de retinol)','solução oral, 150.000 UI/mL frasco'),
(754,'ribavirina','cápsula 250 mg'),
(755,'rifabutina','cápsula 150 mg'),
(756,'rifampicina','cápsula 300 mg'),
(757,'rifampicina','suspensão oral 20mg/mL(2%), frasco'),
(758,'rifampicina + isoniazida','comprimido 150 mg + 75mg'),
(759,'rifampicina + isoniazida','comprimido 300 mg + 150mg'),
(760,'rifampicina + isoniazida','comprimido dispersível, 75 mg + 50mg'),
(761,'rifampicina + isoniazida + pirazinamida','comprimido (75 + 50 + 150)mg'),
(762,'rifampicina + isoniazida + pirazinamida + etambutol (cloridrato de etambutol)','comprimido (150 + 75 +
400 + 275)mg'),
(763,'rifapentina','comprimido, 150mg'),
(764,'riluzol','comprimido 50 mg'),
(765,'risanquinumabe','solução injetável, 75mg/0,83mL frasco ampola'),
(766,'risedronato','comprimido 35 mg'),
(767,'risperidona','comprimido 1 mg'),
(768,'risperidona','comprimido 2 mg'),
(769,'ritonavir','comprimido 100 mg'),
(770,'rituximabe','injetável, 100 mg frasco ampola'),
(771,'rituximabe','injetável, 500 mg frasco ampola'),
(772,'rivaroxabana','comprimido 15 mg'),
(773,'','comprimido 20mg'),
(774,'rivastigmina','cápsula 1,5 mg'),
(775,'rivastigmina','cápsula 3 mg'),
(776,'rivastigmina','cápsula 4,5 mg'),
(777,'rivastigmina','cápsula 6 mg'),
(778,'rivastigmina','solução oral, 2mg/mL frasco com 120 mL'),
(779,'rivastigmina','adesivo transdérmico 9 mg'),
(780,'rivastigmina','adesivo transdérmico 18 mg'),
(781,'sacarato de hidróxido férrico','injetável, 20 mg/mL frasco com 5 mL'),
(782,'sacubitril + valsartana','comprimido 24 mg + 26mg'),
(783,'sacubitril + valsartana','comprimido 49 mg + 51mg'),
(784,'sacubitril + valsartana','comprimido 97 mg + 103mg'),
(785,'sais para reidratação oral','pó para solução oral
(cloreto de sódio, glicose anidra, cloreto de potássio, citrato de sódio di-hidratado)'),
(786,'salbutamol (sulfato de salbutamol)','aerossol oral, 100 mcg/dose'),
(787,'salbutamol (sulfato de salbutamol)','solução para inalação,
5 mg/mL'),
(788,'salbutamol (sulfato de salbutamol)','injetável, 0,5 mg/mL ampola'),
(789,'salbutamol','spray aerossol, 100 mcg/dose frasco com 200 doses'),
(790,'salgueiro (Salix alba
L. )','comprimido, elixir e solução oral (60 a 240 mg de salicina - dose diária)'),
(791,'salmeterol + fluticasona','suspensão oral, spray (25+125) mcg/dose frasco com 120 doses'),
(792,'salmeterol + fluticasona','pó inalatório, (50+250) mcg/dose frasco com 60 doses'),
(793,'sapropterina (dicloridrato de sapropterina)','comprimido 100 mg'),
(794,'selegilina (cloridrato de selegilina)','comprimido 5 mg'),
(795,'seringas com agulha acoplada para aplicação de insulina','unidade'),
(796,'sevelamer (cloridrato de sevelâmer)','comprimido 800 mg'),
(797,'sildenafila','comprimido 20 mg'),
(798,'sildenafila','comprimido 25 mg'),
(799,'sildenafila','comprimido 50 mg'),
(800,'sinvastatina','comprimido 10 mg'),
(801,'sinvastatina','comprimido 20 mg'),
(802,'sinvastatina','comprimido 40 mg'),
(803,'sirolimo','drágea 1 mg'),
(804,'sirolimo','drágea 2 mg'),
(805,'sirolimo','solução oral, 1 mg/mL frasco'),
(806,'sistema de nebulização para uso do medicamento Pentamidina','sistema de nebulização
com bocal, conector em Y, tendo uma das extremidades válvula unidirecional que permite apenas fluxo inspiratório'),
(807,'sofosbuvir','comprimido 400 mg'),
(808,'sofosbuvir + velpatasvir','comprimidos (400 + 100)mg'),
(809,'solução ringer + lactato','injetável (lactato de sódio 3 mg/mL + cloreto de
sódio 6 mg/mL + cloreto de potássio 0,3 mg/mL + cloreto de cálcio 0,2
mg/mL)'),
(810,'solução salina hipertônica','injetável, 7% ampola'),
(811,'somatropina','injetável, 4 UI frasco ampola'),
(812,'somatropina','injetável, 12 UI frasco ampola'),
(813,'somatropina','injetável, 16 UI frasco ampola *item indisponível, aguardando disponibilidade pelo MS'),
(814,'soro antiaracnídico (Loxosceles e Phoneutria) e Tityus)','injetável,
imunoglobulinas que neutralizam, no mínimo, 1,5 dose mínima mortal (DMM) de veneno de Tityus serrulatus  (1,5 DMM/mL), 1,5 DMM de
veneno de Phoneutria nigriventer  (1,5 DMM/mL) e 15 dose mínima necrosante (DMN)de veneno de Loxosceles gaucho  (15
DMN/mL) ampola'),
(815,'soro antibotrópico (pentavalente)','injetável, imunoglobulinas (IgG) que neutralizam, no mínimo, 5 mg de veneno de  Bothrops jararaca  (5 mg/mL) ampola'),
(816,'soro antibotrópico (pentavalente) e anticrotálico','injetável, imunoglobulinas (IgG) que neutralizam, no mínimo, 5 mg de veneno de  Bothrops jararaca  e a 1,5 mg de veneno de Crotalus durissus terrifcus  (5 mg/mL e 1,5 mg/mL) ampola'),
(817,'soro antibotrópico (pentavalente) e antilaquético','injetável, imunoglobulinas (IgG) que neutralizam, no mínimo, 5 mg de veneno de  Bothrops jararaca  e 3 mg de veneno de Lachesis muta  (5 mg/mL e 3 mg/mL) ampola'),
(818,'soro antibotulínico AB (bivalente)','injetável,
imunoglobulinas (IgG) que neutralizam, no mínimo, 375 UI de toxina botulínica tipo A e 275 UI de toxina botulínica tipo B (375 UI/mL e 275 UI/mL) ampola'),
(819,'soro anticrotálico','injetável, imunoglobulinas (IgG) que neutralizam, no mínimo, 1,5 mg de veneno de Crotalus durissus  terrifcus (1,5 mg/mL) ampola'),
(820,'soro antidiftérico','injetável, imunoglobulinas (IgG) que neutralizam, no mínimo, 1.000UI de toxina diftérica (1.000 UI/mL) ampola'),
(821,'soro antielapídico','injetável, imunoglobulinas (IgG) que neutralizam, no mínimo, 1,5 mg de veneno de Micrurus frontalis  (1,5 mg/mL) ampola'),
(822,'soro antiescorpiônico','injetável, imunoglobulinas que neutralizam, no mínimo, 1,5 dose mínima mortal (DMM) de veneno de Tityus serrulatus  (1,5 DMM/mL) ampola'),
(823,'soro antilonômico','injetável, imunoglobulinas que neutralizam, no mínimo, 0,35 mg de veneno de Lonomia obliqua  (0,35 mg/mL) ampola'),
(824,'soro antiloxoscélico','injetável,
imunoglobulinas que neutralizam, no mínimo, 15 dose mínima necrosante (DMN) de veneno de aranhas das espécies Loxosceles laeta, Lxosceles gaucho e Loxosceles
intermedia (15 DMN/mL)
ampola'),
(825,'soro antirrábico','injetável, imunoglobulinas que neutralizam, no mínimo, 200 UI de vírus da raiva (200 UI/mL) ampola'),
(826,'soro antitetânico','injetável, imunoglobulinas que neutralizam, no mínimo,
1.000 UI de toxina tetânica'),
(827,'sulfadiazina','comprimido 500 mg'),
(828,'sulfadiazina de prata','creme 10 mg/g (1%)'),
(829,'sulfametoxazol + trimetoprima','comprimido 400 mg +
80 mg'),
(830,'sulfametoxazol + trimetoprima','suspensão oral,
(40 + 8) mg/mL frasco'),
(831,'sulfametoxazol + trimetoprima','injetável, (80 + 16 mg)/Ml ampola'),
(832,'sulfassalazina','comprimido 500 mg'),
(833,'sulfato de magnésio','pó para solução oral'),
(834,'sulfato de magnésio','injetável 0,81 mEq/mL
Mg++ (10%)'),
(835,'sulfato de magnésio','injetável, 4,05 mEq/mL
Mg++ (50%)'),
(836,'sulfato de zinco','comprimido mastigável 10 mg'),
(837,'sulfato de zinco','xarope, 4 mg/mL frasco'),
(838,'sulfato de zinco','injetável, 200 mcg/dose ampola'),
(839,'sulfato ferroso','comprimido 40 mg'),
(840,'sulfato ferroso','solução oral, 25 mg/mL frasco'),
(841,'sulfato ferroso','xarope, 5 mg/mL frasco'),
(842,'tacrolimo','cápsula 1 mg'),
(843,'tacrolimo','cápsula 5 mg'),
(844,'tacrolimo','injetável, 5 mg/mL frasco ampola'),
(845,'tafamidis','cápsula 20 mg'),
(846,'tafenoquina (succinato de tafenoquina)','comprimido 150 mg'),
(847,'talidomida','comprimido 100 mg'),
(848,'teclozana','comprimido 500 mg'),
(849,'teclozana','suspensão oral, 10 mg/mL frasco'),
(850,'teicoplanina','injetável, 400 mg frasco ampola'),
(851,'tenecteplase','injetável, 30 mg frasco ampola'),
(852,'tenecteplase','injetável, 40 mg frasco ampola'),
(853,'tenecteplase','injetável, 50 mg frasco ampola'),
(854,'tenofovir (fumarato de tenofovir desoproxila)','comprimido 300 mg'),
(855,'tenofovir (fumarato de tenofovir desoproxila)
+ entricitabina','comprimido (300 + 200)mg'),
(856,'tenofovir (fumarato de tenofovir desoproxila)
+ lamivudina','comprimido (300 + 300)mg'),
(857,'tenofovir (fumarato de tenofovir desoproxila)
+ lamivudina +
efavirenz','comprimido (300 + 300
+ 600)mg'),
(858,'tenofovir (hemifumarato de tenofovir alafenamida)','comprimido 25 mg'),
(859,'teriflunomida','comprimido 14 mg'),
(860,'terizidona','cápsula 250 mg'),
(861,'tetraciclina (cloridrato de tetraciclina)','cápsula 500 mg'),
(862,'tetraciclina (cloridrato de tetraciclina)','pomada oftálmica 10mg/g (1%)'),
(863,'tiamazol','comprimido 5mg'),
(864,'tiamazol','comprimido 10mg'),
(865,'tiamina (cloridrato de tiamina)','comprimido 300 mg'),
(866,'timolol (maleato de timolol)','solução oftálmica, 2,5mg/mL (0,25%)
frasco'),
(867,'timolol (maleato de timolol)','solução oftálmica, 5mg/mL (0,5%) frasco'),
(868,'tiotrópio (brometo de tiotrópio)','solução inalatória, 2,5mcg/dose frasco com 4 mL (60 DOSES)'),
(869,'tiotrópio + olodaterol','solução inalatória, (2,5mcg + 2,5mcg)/dose frasco com 60 doses'),
(870,'tipranavir','cápsula 250 mg'),
(871,'tipranavir','solução oral, 100 mg/mL'),
(872,'tiras reagentes de medida de glicemia capilar','unidade'),
(873,'tirofibana (cloridrato de tirofibana)','injetável, 0,25 mg/mL frasco ampola'),
(874,'tobramicina','solução para inalação, 300mg frasco'),
(875,'tobramicina','cápsula inalatória 28 mg'),
(876,'tocilizumabe','injetável, 20 mg/mL frasco ampola com 4mL'),
(877,'tofacitinibe','comprimido 5 mg'),
(878,'tolterodina (tartarato de tolterodina)','cápsula de liberação prolongada 4 mg *item indisponível  no mercado nacional por parte do
fabricante.'),
(879,'topiramato','comprimido 25 mg'),
(880,'topiramato','comprimido 50 mg'),
(881,'topiramato','comprimido 100 mg'),
(882,'toxina botulínica tipo A','injetável, 100 UI frasco ampola'),
(883,'toxina botulínica tipo A','injetável, 500 UI frasco ampola'),
(884,'tramadol (cloridrato de tramadol)','comprimido 50 mg'),
(885,'trastuzumabe','comprimido 150 mg'),
(886,'travoprosta','solução oftálmica, 0,04 mg/mL frasco com 2,5 mL'),
(887,'trientina','cápsula 250 mg'),
(888,'triexifenidil (cloridrato de triexifenidil)','comprimido 5 mg *item
atualmente sem demanda. Após abertura (fluxo NP)e deferimento do processo, seu fornecimento deverá aguardar finalização de processo'),
(889,'triptorrelina','injetável, 3,75 mg frasco ampola'),
(890,'triptorrelina','injetável, 11,25 mg frasco ampola *item atualmente sem demanda.
Após abertura (fluxo NP)e deferimento do processo, seu fornecimento deverá aguardar finalização de processo licitatório.'),
(891,'unha-de-gato [Uncaria tomentosa (Willd ex Roem.& Schult.)]','cápsula, comprimido e gel (0,9 mg de alcaloides oxindólicos pentaclíclicos)'),
(892,'umeclídio + vilaterol','pó para inalação oral, (62,5mcg + 25mcg)/dose frasco com 60 doses'),
(893,'Upadacitinibe','comprimidos 15 mg'),
(894,'Ustequinumabe','injetável, 45mg frasco ampola'),
(895,'vacina adsorvida difteria e tétano adulto','injetável, frasco ampola'),
(896,'vacina adsorvida difteria e tétano infantil','injetável, frasco ampola'),
(897,'vacina adsorvida difteria, tétano e pertussis','injetável, frasco ampola'),
(898,'vacina adsorvida difteria, tétano e pertussis  (acelular) adulto','injetável, frasco ampola'),
(899,'vacina adsorvida difteria, tétano e pertussis  (acelular) infantil','injetável, frasco ampola'),
(900,'vacina adsorvida difteria, tétano, pertussis , hepatite B (recombinante) e Haemophilus Influenzae  B (conjugada)','injetável, frasco ampola'),
(901,'vacina adsorvida hepatite A (inativada) adulto','injetável, frasco ampola'),
(902,'vacina adsorvida hepatite A (inativada) infantil','injetável, frasco ampola'),
(903,'vacina BCG','injetável, frasco ampola'),
(904,'vacina cólera (inativada)','suspensão oral, frasco'),
(905,'vacina febre amarela (atenuada)','injetável, frasco ampola'),
(906,'vacina febre tifóide (polissacarídica)','injetável, ampola'),
(907,'vacina Haemophilus Influenzae  B (conjugada)','injetável, frasco ampola'),
(908,'vacina hepatite B (recombinante)','injetável, frasco ampola'),
(909,'vacina
influenza trivalente (fragmentada, inativada)','injetável, frasco ampola'),
(910,'vacina meningocócica ACWY (conjugada)','injetável, frasco ampola'),
(911,'vacina meningocócica C','injetável, frasco ampola'),
(912,'vacina papilomavírus humano 6, 11, 16 e 18 (recombinante)','injetável, frasco ampola'),
(913,'vacina pneumocócica 10-valente (conjugada)','injetável, frasco ampola'),
(914,'vacina pneumocócica 13-valente (conjugada)','injetável, frasco ampola'),
(915,'vacina pneumocócica 23-valente (polissacarídica)','injetável, ampola'),
(916,'vacina poliomielite 1, 2
e 3 (inativada)','injetável, ampola'),
(917,'vacina poliomielite 1 e 3 (atenuada)','suspensão oral, frasco'),
(918,'vacina raiva (inativada)','injetável, frasco ampola'),
(919,'vacina rotavírus humano G1P [8] (atenuada)','suspensão oral, frasco'),
(920,'vacina sarampo, caxumba, rubéola','injetável, frasco ampola'),
(921,'vacina sarampo, caxumba, rubéola e varicela (atenuada)','injetável, frasco ampola'),
(922,'vacina varicela (atenuada)','injetável, frasco ampola'),
(923,'valaciclovir','comprimido 500 mg'),
(924,'varfarina sódica','comprimido 1 mg'),
(925,'varfarina sódica','comprimido 5 mg'),
(926,'vedolizumabe','injetável, 300mg frasco'),
(927,'verapamil (cloridrato de verapamil)','comprimido 80 mg'),
(928,'verapamil (cloridrato de verapamil)','comprimido 120 mg'),
(929,'verapamil (cloridrato de verapamil)','injetável, 2,5 mg/mL ampola'),
(930,'vigabatrina','comprimido 500 mg'),
(931,'voriconazol','injetável 200 mg, frasco- ampola'),
(932,'zanamivir','pó  inalante oral 5 mg'),
(933,'zidovudina','cápsula 100 mg
injetável, 10 mg/mL frasco'),
(934,'zidovudina','solução oral, 10 mg/mL frasco'),
(935,'zidovudina +','comprimido 300 mg +'),
(936,'lamivudina','150 mg'),
(937,'ziprasidona','cápsula 40 mg'),
(938,'ziprasidona','cápsula 80 mg');